[phases.setup]
nixPkgs = ["python39", "nodejs", "npm"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd $NIXPACKS_BUILD_DIR && npm install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "gunicorn backend.app:app"